# Generated by Django 3.2 on 2023-02-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите Ваш комментарий к отзыву', verbose_name='Комментарий'),
        ),
    ]
